- name: Install packages and configure Debian 12/13
  hosts: localhost
  vars_files:
    - packages.yml
  tasks:
    - name: System configuration
      become: true
      block:
        - name: Install and remove repository packages
          ansible.builtin.import_tasks: tasks/install_repo_packages.yml
        - name: Install GitHub packages
          ansible.builtin.import_tasks: tasks/install_github_packages.yml
        - name: Configure system settings and user environment
          ansible.builtin.import_tasks: tasks/configure_system_settings.yml

    - name: User configuration
      become: false
      block:
        - name: Install Python packages
          ansible.builtin.import_tasks: tasks/install_python_packages.yml
        - name: Install Rust toolchain and AIChat
          ansible.builtin.import_tasks: tasks/install_rust.yml
        - name: Stow dotfiles
          ansible.builtin.import_tasks: tasks/stow_dotfiles.yml
        - name: Configure Pipewire
          ansible.builtin.import_tasks: tasks/setup_pipewire.yml
        - name: Update .bashrc and .profile
          ansible.builtin.import_tasks: tasks/update_bashrc.yml
        - name: Setup Gnome
          ansible.builtin.import_tasks: tasks/setup-gnome.yml
        - name: Download and install yabridge
          ansible.builtin.unarchive:
            src: "https://github.com/robbert-vdh/yabridge/releases/download/{{ yabridge_version }}/yabridge-{{ yabridge_version }}.tar.gz"
            dest: "{{ ansible_env.HOME }}/.local/share"
            remote_src: true
