- name: Install packages and configure Debian 12/13 as root
  hosts: localhost
  become: true
  vars_files:
    - packages.yml
  tasks:
    - name: Remove unwanted applications
      ansible.builtin.import_tasks: tasks/remove_unwanted_apps.yml

    - name: Install repository packages
      ansible.builtin.import_tasks: tasks/install_repo_packages.yml

    - name: Install GitHub packages and binary executables
      ansible.builtin.import_tasks: tasks/install_github_packages.yml

    - name: Create symbolic links and add user to pipewire group
      ansible.builtin.import_tasks: tasks/create_symlinks.yml

- name: Configure user environment
  hosts: localhost
  become: false
  vars_files:
    - packages.yml
  tasks:
    - name: Install Python packages as user
      ansible.builtin.import_tasks: tasks/install_python_packages.yml

    - name: Install Rust toolchain and AIChat
      ansible.builtin.import_tasks: tasks/install_rust.yml

    - name: Stow dotfiles
      ansible.builtin.import_tasks: tasks/stow_dotfiles.yml

    - name: Configure Pipewire
      ansible.builtin.import_tasks: tasks/setup_pipewire.yml

    - name: Update bashrc
      ansible.builtin.import_tasks: tasks/update_bashrc.yml

    - name: Download and install yabridge as user
      ansible.builtin.unarchive:
        src: "https://github.com/robbert-vdh/yabridge/releases/download/{{ yabridge_version }}/yabridge-{{ yabridge_version }}.tar.gz"
        dest: "{{ ansible_env.HOME }}/.local/share"
        remote_src: true
