- name: Install packages and configure Debian 13
  hosts: localhost
  vars_files:
    - packages.yml
  tasks:
    - name: System configuration
      become: true
      block:
        - name: Install and remove repository packages
          ansible.builtin.import_tasks: tasks/install_repo_packages.yml
        - name: Install GitHub packages
          ansible.builtin.import_tasks: tasks/install_github_packages.yml
        - name: Configure system settings and user environment
          ansible.builtin.import_tasks: tasks/configure_system_settings.yml

    - name: User configuration
      become: false
      block:
        - name: Stow dotfiles
          ansible.builtin.import_tasks: tasks/stow_dotfiles.yml
        - name: Configure Pipewire
          ansible.builtin.import_tasks: tasks/setup_pipewire.yml
        - name: Update .bashrc and .profile
          ansible.builtin.import_tasks: tasks/update_bashrc.yml

        - name: Download and install yabridge
          ansible.builtin.unarchive:
            src: "https://github.com/robbert-vdh/yabridge/releases/download/{{ yabridge_version }}/yabridge-{{ yabridge_version }}.tar.gz"
            dest: "{{ ansible_env.HOME }}/.local/share"
            remote_src: true

        - name: Install or upgrade Python packages
          community.general.pipx:
            name: "{{ item }}"
            executable: pipx
            state: latest
          loop: "{{ python_packages }}"

        - name: Configure GNOME settings
          community.general.dconf:
            key: "{{ item.key }}"
            value: "{{ item.value }}"
          loop:
            - {
                key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled",
                value: "true",
              }
            - {
                key: "/org/gnome/shell/extensions/auto-move-windows/application-list",
                value: "['org.gnome.Calendar.desktop:2', 'org.signal.Signal.desktop:2', 'firefox-esr.desktop:3']",
              }
