- name: Install packages and set up Debian 13 as root
  hosts: localhost
  become: true
  vars_files:
    - packages.yml
  tasks:
    - name: Remove unwanted applications
      ansible.builtin.import_tasks: tasks/remove_unwanted_apps.yml

    - name: Install repository packages
      ansible.builtin.import_tasks: tasks/install_repo_packages.yml

    - name: Install GitHub packages and binary executables
      ansible.builtin.import_tasks: tasks/install_github_packages.yml

    - name: Create symlinks
      ansible.builtin.import_tasks: tasks/create_symlinks.yml

    - name: Install Rust
      ansible.builtin.import_tasks: tasks/install_rust.yml

- name: Install packages and set up Debian 13 as user
  hosts: localhost
  become: false
  vars_files:
    - packages.yml
  tasks:
    - name: Stow dotfiles
      ansible.builtin.import_tasks: tasks/stow_dotfiles.yml

    - name: Set up Pipewire
      ansible.builtin.import_tasks: tasks/setup_pipewire.yml

    - name: Update bashrc
      ansible.builtin.import_tasks: tasks/update_bashrc.yml

    - name: Configure MIME applications
      ansible.builtin.import_tasks: tasks/configure-mime-applications.yml

    - name: Install Python packages
      block:
        - name: Install packages with pipx
          ansible.builtin.command: pipx install {{ item }}
          loop: "{{ python_packages }}"
          args:
            creates: "{{ ansible_env.HOME }}/.local/pipx/venvs/{{ item }}"

        - name: Run pipx ensurepath
          ansible.builtin.command: pipx ensurepath
          changed_when: false

    - name: Download and install yabridge
      ansible.builtin.unarchive:
        src: "https://github.com/robbert-vdh/yabridge/releases/download/{{ yabridge_version }}/yabridge-{{ yabridge_version }}.tar.gz"
        dest: "{{ ansible_env.HOME }}/.local/share"
        remote_src: true
