- hosts: localhost
  tasks:
    - name: Install shell-gpt and yt-dlp with pipx
      ansible.builtin.command: pipx install {{ item }}
      loop:
        - shell-gpt
        - yt-dlp

    - name: Run pipx ensurepath
      ansible.builtin.command: pipx ensurepath

    - name: Install Rust and rust-analyzer
      block:
        - name: Install Rust and Rust Analyzer
          ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && . "{{ ansible_env.HOME }}/.cargo/env" && rustup component add rust-analyzer
          args:
            creates: "{{ ansible_env.HOME }}/.cargo/env"
