- name: Create symlinks
  block:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Create symlink for lldb-dap-19 as lldb-dap
      ansible.builtin.file:
        src: /usr/bin/lldb-dap-19
        dest: /usr/bin/lldb-dap
        state: link
      when: "'lldb-19' in ansible_facts.packages"

    - name: Create symlink for batcat as bat
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
      when: "'bat' in ansible_facts.packages"

- name: Switch to Zsh for the default shell
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh

- name: Create default.conf for keyd
  ansible.builtin.copy:
    content: |
      [ids]
      *

      [main]
      # Maps capslock to escape when pressed and control when held.
      capslock = overload(control, esc)
    dest: /etc/keyd/default.conf

- name: Create Hugo Zsh completions
  block:
    - name: Generate Hugo completion for zsh
      ansible.builtin.command: hugo completion zsh
      register: hugo_completion
      changed_when: false

    - name: Write Hugo completion to file
      ansible.builtin.copy:
        content: "{{ hugo_completion.stdout }}"
        dest: /usr/share/zsh/vendor-completions/_hugo
