- name: Configure MIME applications
  block:
    - name: Ensure MIME config directory exists
      ansible.builtin.file:
        path: "~/.config"
        state: directory

    - name: Ensure mimeapps.list exists
      ansible.builtin.file:
        path: "~/.config/mimeapps.list"
        state: touch

    - name: Backup mimeapps.list
      ansible.builtin.copy:
        src: "~/.config/mimeapps.list"
        dest: "~/.config/mimeapps.list.backup"

    - name: Write default and added associations to mimeapps.list
      ansible.builtin.blockinfile:
        path: "~/.config/mimeapps.list"
        block: |
          [Default Applications]
          video/x-matroska=mpv.desktop
          video/mp4=mpv.desktop
          audio/x-opus+ogg=mpv.desktop
          text/vnd.trolltech.linguist=helix.desktop
          application/toml=helix.desktop
          text/plain=helix.desktop
          text/x-python=helix.desktop
          application/json=helix.desktop
          application/javascript=helix.desktop
          audio/flac=mpv.desktop
          application/x-shellscript=helix.desktop
          audio/prs.sid=sidplayfp.desktop
          text/csv=libreoffice-calc.desktop
          video/mpeg=mpv.desktop

          [Added Associations]
          video/x-matroska=mpv.desktop;
          video/mp4=mpv.desktop;
          audio/x-opus+ogg=mpv.desktop;
          text/vnd.trolltech.linguist=helix.desktop;
          application/toml=helix.desktop;
          text/plain=helix.desktop;
          text/x-python=helix.desktop;
          application/json=helix.desktop;
          application/javascript=helix.desktop;
          audio/flac=mpv.desktop;
          application/x-shellscript=helix.desktop;
          audio/prs.sid=sidplayfp.desktop;
          text/csv=libreoffice-calc.desktop;
          video/mpeg=mpv.desktop;
        create: true

    - name: Update desktop database if mimeapps.list changed
      ansible.builtin.command: update-desktop-database ~/.local/share/applications
