- name: Gather package facts for conditional setup
  ansible.builtin.package_facts:
    manager: auto

- name: Create symlinks
  block:
    - name: Create symlink for lldb-dap-19 as lldb-dap
      ansible.builtin.file:
        src: /usr/bin/lldb-dap-19
        dest: /usr/bin/lldb-dap
        state: link
      when: "'lldb-19' in ansible_facts.packages"

    - name: Create symlink for batcat as bat
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
      when: "'bat' in ansible_facts.packages"

- name: Check if nnn plugins directory exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/nnn/plugins"
  register: plugins_dir

- name: Install nnn plugins if nnn is installed and plugins directory does not exist
  become: false
  ansible.builtin.shell: sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)"
  when: "'nnn' in ansible_facts.packages and not plugins_dir.stat.exists"

- name: Configure Zsh and Hugo Completions
  when:
    - "'zsh' in ansible_facts.packages"
  block:
    - name: Switch the default shell to Zsh
      ansible.builtin.user:
        name: "{{ lookup('ansible.builtin.env', 'USER') }}"
        shell: /usr/bin/zsh

    - name: Generate Hugo completion for Zsh
      ansible.builtin.command: hugo completion zsh
      register: hugo_completion
      changed_when: false

    - name: Write Hugo completion to system-wide Zsh completions
      ansible.builtin.copy:
        content: "{{ hugo_completion.stdout }}"
        dest: /usr/share/zsh/vendor-completions/_hugo

- name: Create default.conf for keyd to map capslock to escape
  ansible.builtin.copy:
    content: |
      [ids]
      *

      [main]
      # Maps capslock to escape when pressed and control when held.
      capslock = overload(control, esc)
    dest: /etc/keyd/default.conf

- name: Add user to the pipewire group to get realtime privileges from /etc/security/limits.d/25-pw-rlimits.conf
  ansible.builtin.user:
    name: "{{ lookup('ansible.builtin.env', 'USER') }}"
    groups: pipewire
    append: true
