- name: Create symlinks
  block:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Create symlink for lldb-dap-19 as lldb-dap
      ansible.builtin.file:
        src: /usr/bin/lldb-dap-19
        dest: /usr/bin/lldb-dap
        state: link
      when: "'lldb-19' in ansible_facts.packages"

    - name: Create symlink for batcat as bat
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
      when: "'bat' in ansible_facts.packages"

# TODO i don't think this works from the testing of debian 13
- name: Create pipewire group
  ansible.builtin.group:
    name: pipewire

- name: Add user to the pipewire group to get realtime privileges from /etc/security/limits.d/25-pw-rlimits.conf
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: pipewire
    append: true
