- name: Install packages with pipx
  community.general.pipx:
    name: "{{ item }}"
    executable: pipx
  loop: "{{ python_packages }}"

- name: Run pipx ensurepath
  ansible.builtin.command: pipx ensurepath
  changed_when: false
