- name: Remove unwanted desktop apps
  ansible.builtin.apt:
    name: "{{ packages_to_remove }}"
    state: absent
    autoremove: true
    purge: true

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Update and upgrade all Debian packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install packages
  block:
    - name: Install Debian packages
      ansible.builtin.apt:
        name: "{{ debian_packages }}"

    - name: Install Flatpak packages
      community.general.flatpak:
        name: "{{ flatpak_packages }}"

    - name: Install NPM global packages
      loop: "{{ npm_packages }}"
      community.general.npm:
        name: "{{ item }}"
        global: true

- name: Install pipewire backport for Debian 12
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "12"
  block:
    - name: Add bookworm backports apt repository
      ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian bookworm-backports main

    - name: Install backports pipewire
      ansible.builtin.apt:
        name: pipewire
        state: latest
        default_release: bookworm-backports
