- name: Install Debian packages directly from Github
  become: true
  vars:
    rclone_version: "1.68.2"
    hugo_version: "0.140.2"
    helix_version: "25.01.1"
  block:
    - name: Download and install rclone
      ansible.builtin.apt:
        deb: "https://github.com/rclone/rclone/releases/download/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-amd64.deb"

    # Must be at least 134.3 to work with Helix https://packages.debian.org/trixie/hugo
    - name: Download and install hugo
      ansible.builtin.apt:
        deb: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_extended_{{ hugo_version }}_linux-amd64.deb"

    - name: Download and install helix
      ansible.builtin.apt:
        deb: "https://github.com/helix-editor/helix/releases/download/{{ helix_version }}/helix_25.1.1-1_amd64.deb"
