- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Update and upgrade all Debian packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install packages
  block:
    - name: Install Debian packages (exclude Debian 13 packages on Debian 12)
      ansible.builtin.apt:
        name: >-
          {{
            (ansible_distribution == 'Debian' and ansible_distribution_major_version == '12')
            | ternary(
                debian_packages,
                debian_packages + debian_13_packages
              )
          }}

    - name: Install Flatpak packages (include extra packages on Debian 12)
      community.general.flatpak:
        name: >-
          {{
            (ansible_distribution == 'Debian' and ansible_distribution_major_version == '12')
            | ternary(
                flatpak_packages + debian_12_flatpak_packages,
                flatpak_packages
              )
          }}

    - name: Install NPM global packages
      loop: "{{ npm_packages }}"
      community.general.npm:
        name: "{{ item }}"
        global: true

- name: Install pipewire backport for Debian 12
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "12"
  block:
    - name: Add bookworm backports apt repository
      ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian bookworm-backports main

    - name: Install backports pipewire
      ansible.builtin.apt:
        name: pipewire
        state: latest
        default_release: bookworm-backports
# - name: Install Blender
#   block:
#     - name: Create directory /usr/local/bin/blender-bin
#       become: true
#       ansible.builtin.file:
#         path: "{{ user_programs }}/blender-bin"
#         state: directory

#     - name: Download Blender and extract archive
#       become: true
#       ansible.builtin.unarchive:
#         src: "https://download.blender.org/release/Blender4.3/blender-4.3.2-linux-x64.tar.xz"
#         dest: "{{ user_programs }}/blender-bin"
#         remote_src: true
#         creates: "{{ user_programs }}/blender-bin/blender"
#         extra_opts:
#           - "--strip-components=1"

#     - name: Create symlink to Blender binary
#       become: true
#       ansible.builtin.file:
#         src: "{{ user_programs }}/blender-bin/blender"
#         dest: "{{ user_programs }}/blender"
#         state: link

#     - name: Copy Blender desktop file
#       ansible.builtin.copy:
#         src: "{{ user_programs }}/blender-bin/blender.desktop"
#         dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/share/applications/blender.desktop"

#     - name: Create ~/.icons directory
#       ansible.builtin.file:
#         path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.icons"
#         state: directory

#     - name: Copy Blender icon
#       ansible.builtin.copy:
#         src: "{{ user_programs }}/blender-bin/blender.svg"
#         dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.icons/blender.svg"
