- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Update and upgrade all Debian packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install Debian packages (exclude Debian 13 packages on Debian 12)
  ansible.builtin.apt:
    name: >-
      {{
        (ansible_distribution == 'Debian' and ansible_distribution_major_version == '12')
        | ternary(
            debian_packages,
            debian_packages + debian_13_packages
          )
      }}

# - name: Install Flatpak packages
#   community.general.flatpak:
#     name: "{{ flatpak_packages }}"

- name: Install Flatpak packages (include extra packages on Debian 12)
  community.general.flatpak:
    name: >-
      {{
        (ansible_distribution == 'Debian' and ansible_distribution_major_version == '12')
        | ternary(
            flatpak_packages + debian_12_flatpak_packages,
            flatpak_packages
          )
      }}

- name: Install NPM global packages
  loop: "{{ npm_packages }}"
  community.general.npm:
    name: "{{ item }}"
    global: true
