- name: Remove unwanted desktop apps
  ansible.builtin.apt:
    name: "{{ packages_to_remove }}"
    state: absent
    autoremove: true
    purge: true

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Update and upgrade all Debian packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install system wide packages
  block:
    - name: Install Debian packages
      ansible.builtin.apt:
        name: "{{ debian_packages }}"

    - name: Install Flatpak packages
      community.general.flatpak:
        name: "{{ flatpak_packages }}"

    - name: Install NPM global packages
      loop: "{{ npm_packages }}"
      community.general.npm:
        name: "{{ item }}"
        global: true

- name: Install or upgrade Python user packages
  become: false
  community.general.pipx:
    name: "{{ item }}"
    executable: pipx
    state: latest
  loop: "{{ python_packages }}"
