- name: Install ltex-ls-plus with JDK
  block:
    - name: Create versioned installation directory for ltex-ls-plus
      ansible.builtin.file:
        path: "{{ bin_install_dir }}/ltex-ls-plus-{{ ltex_ls_plus_version }}"
        state: directory

    - name: Extract ltex-ls-plus
      ansible.builtin.unarchive:
        src: "https://github.com/ltex-plus/ltex-ls-plus/releases/download/{{ ltex_ls_plus_version }}/ltex-ls-plus-{{ ltex_ls_plus_version }}-linux-x64.tar.gz"
        dest: "{{ bin_install_dir }}/ltex-ls-plus-{{ ltex_ls_plus_version }}"
        remote_src: true
        extra_opts:
          - "--strip-components=2" # removes /./ltex-ls-plus-18.4.0/
          - "--wildcards"
          - "*/bin/*" # */ is needed to deal with strange /./ structure
          - "*/lib/*"
          - "*/jdk-*/*"
        creates: "{{ bin_install_dir }}/ltex-ls-plus-{{ ltex_ls_plus_version }}/bin/ltex-ls-plus"

    - name: Create symbolic links to versioned binary
      ansible.builtin.file:
        src: "{{ bin_install_dir }}/ltex-ls-plus-{{ ltex_ls_plus_version }}/bin/ltex-ls-plus"
        dest: "{{ bin_install_dir }}/ltex-ls-plus"
        state: link
        force: true

- name: Install executables
  block:
    - name: Install marksman
      ansible.builtin.get_url:
        url: "https://github.com/artempyanykh/marksman/releases/download/{{ marksman_version }}/marksman-linux-x64"
        dest: "{{ bin_install_dir }}/marksman"
        checksum: "sha256:{{ marksman_shasum }}"
        mode: "0755"

- name: Install .deb packages
  ansible.builtin.apt:
    deb: "{{ item.url }}"
  loop:
    - name: rclone
      url: "https://github.com/rclone/rclone/releases/download/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-amd64.deb"
    - name: hugo
      url: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_extended_{{ hugo_version }}_linux-amd64.deb"
    - name: helix
      url: "{{ playbook_dir }}/extras/helix_25.7.1-1_amd64_d0218f7e78bc0c3af4b0995ab8bda66b9c542cf3.deb"
    - name: nnn
      url: "{{ playbook_dir }}/extras/nnn_5.1_amd64_nerd_fonts.deb"
