- name: Install packages with pipx
  ansible.builtin.command: pipx install {{ item }}
  loop: "{{ python_packages }}"
  args:
    creates: "{{ ansible_env.HOME }}/.local/pipx/venvs/{{ item }}"

- name: Run pipx ensurepath
  ansible.builtin.command: pipx ensurepath
  changed_when: false
