- name: Remove unwanted desktop apps
  become: true
  vars_files:
    - packages.yml
  ansible.builtin.apt:
    name: "{{ packages_to_remove }}"
    state: absent
    autoremove: true
    purge: true
