- name: Enable GNOME Night Light
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
    state: present

- name: Configure GNOME Auto Move Windows extension workspace rules
  community.general.dconf:
    key: "/org/gnome/shell/extensions/auto-move-windows/application-list"
    value: "['org.gnome.Calendar.desktop:2', 'org.signal.Signal.desktop:2', 'firefox-esr.desktop:3']"
    state: present
