- name: Enable GNOME Night Light
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
    state: present

- name: Configure GNOME Auto Move Windows extension workspace rules
  community.general.dconf:
    key: "/org/gnome/shell/extensions/auto-move-windows/application-list"
    value: "['kitty.desktop:1', 'org.gnome.Calendar.desktop:2', 'org.signal.Signal.desktop:3', 'firefox-esr.desktop:4']"
    state: present
