- name: Create ~/.dotfiles directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.dotfiles"
    state: directory

- name: Copy dotfiles to home directory
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dotfiles/"
    dest: "{{ ansible_env.HOME }}/.dotfiles/"

# - name: Run stow BROKEN because i don't think it cds inside the shell?
#   ansible.builtin.command:
#     chdir: "{{ ansible_env.HOME }}/.dotfiles"
#     cmd: >
#       stow --target={{ ansible_env.HOME }} */ --verbose=2
#   register: result
#   changed_when: 'result.stderr is search("LINK: ")'
#   failed_when: 'result.rc != 0 and "Conflicting" in result.stderr'

- name: Run stow
  ansible.builtin.command:
    chdir: "{{ ansible_facts['user_dir'] }}/.dotfiles"
    cmd: >
      stow --target={{ ansible_facts['user_dir'] }} autostart helix mpv shell pandoc kitty lazygit keepassxc aichat sidplayfp marksman config
      --verbose=2
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
  failed_when: 'result.rc != 0 and "Conflicting" in result.stderr'
