- name: Create ~/.dotfiles directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.dotfiles"
    state: directory

- name: Copy dotfiles to home directory
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dotfiles/"
    dest: "{{ ansible_env.HOME }}/.dotfiles/"

- name: Run stow on every directory in ~/.dotfiles
  ansible.builtin.shell:
    chdir: "{{ ansible_facts['user_dir'] }}/.dotfiles"
    cmd: stow --target="{{ ansible_facts['user_dir'] }}" * --verbose=2
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
  failed_when: 'result.rc != 0 and "Conflicting" in result.stderr'
