- name: Update .bashrc by appending extra config
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', 'bashrc.bash') }}"
    path: "{{ ansible_env.HOME }}/.bashrc"
    backup: true
