- name: Update .bashrc by appending extra config
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', 'bashrc.bash') }}"
    path: "{{ ansible_env.HOME }}/.bashrc"
    backup: true

- name: Update .profile with shared environment variables for bash and zsh
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', 'profile.sh') }}"
    path: "{{ ansible_env.HOME }}/.profile"
    backup: true
