- name: Update .bashrc by appending extra config
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', './bashrc.bash') }}"
    path: "{{ ansible_facts['user_dir'] }}/.bashrc"
    backup: true
