theme = "dark_plus"

# Normal Mode

[keys.normal]
G = "goto_file_end" # vim
Z = { Z = ":wq", Q = ":q!" } # vim
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"] # vim
"#" = "toggle_comments"
"F5" = ":reload"

# Insert Mode

[keys.insert]
j = { k = "normal_mode" }
C-backspace = "delete_word_backward"

# Select Mode

[keys.select]
G = "goto_file_end" # vim

# Space Mode

[keys.normal.space]
w = ":write"
"." = "file_picker_in_current_buffer_directory"
"@" = ["select_all", ":pipe sort -t@ -k2,2"]
"+" = ["select_all", ":pipe sort -t+ -k2,2"]

[keys.normal.space.t]
f = ":toggle auto-format"
i = ":toggle lsp.display-inlay-hints"
s = ":toggle soft-wrap.enable"
w = ":toggle whitespace.render all none"
z = ":toggle gutters.line-numbers.min-width 48 3"

[keys.normal.space.c]
r = ":sh kitty @ send-text --match 'title:^Terminal' 'cargo run\n'"
t = ":sh kitty @ send-text --match 'title:^Terminal' 'clear\ncargo test\n'"
T = ":pipe-to xargs -I {} kitty @ send-text --match 'title:^Terminal' 'cargo test {}\n'"

# Editor

[editor]
color-modes = true

[editor.cursor-shape]
insert = "bar" # change cursor shape in insert mode

[editor.file-picker]
hidden = false # don't ignore hidden files
follow-symlinks = false

[editor.statusline]
center = ["version-control"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
