theme = "dark_plus"

[keys.normal]
G = "goto_file_end" # vim
Z = { Z = ":wq", Q = ":q!" } # vim
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"] # vim
"#" = "toggle_comments"

[keys.normal.space]
w = ":write"
t = { "@" = ["select_all", ":pipe sort -t@ -k2,2"], "+" = ["select_all", ":pipe sort -t+ -k2,2"], f = ":toggle auto-format", i = ":toggle lsp.display-inlay-hints", l = ":toggle line-number absolute relative", s = ":toggle soft-wrap.enable", w = ":toggle whitespace.render all none", z = ":toggle gutters.line-numbers.min-width 48 3" }
c = { r = ":sh kitty @ send-text --match 'title:^Terminal' cargo run \\\\n", t = ":sh kitty @ send-text --match 'title:^Terminal' 'clear \\ncargo test \\n'" }
"." = "file_picker_in_current_buffer_directory"

[keys.insert]
j = { k = "normal_mode" }
C-backspace = "delete_word_backward"

[keys.select]
G = "goto_file_end" # vim

[editor]
color-modes = true

# [editor.cursor-shape]
# insert = "bar" # change cursor shape in insert mode

[editor.file-picker]
hidden = false # don't ignore hidden files
follow-symlinks = false

[editor.statusline]
center = ["version-control"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true