theme = "dark_plus"

[keys.normal]
"tab" = "expand_selection"
"S-tab" = "shrink_selection"
G = "goto_file_end" # vim
Z = { Z = ":wq", Q = ":q!" } # vim
"F5" = ":reload"

[keys.select]
G = "goto_file_end" # vim

[keys.normal.space]
w = ":write"
q = ":quit"
"." = "file_picker_in_current_buffer_directory"
"@" = ["select_all", ":pipe sort -t@ -k2,2"]
"+" = ["select_all", ":pipe sort -t+ -k2,2"]
G = [":pipe-to cat > /tmp/helix-gpt", ":append-output cat /tmp/helix-gpt | sgpt --role tr --no-cache 'Improve this writing'"]

[keys.normal.C-t]
l = ":sh kitty @ focus-window --match 'title:lazygit and state:parent_active' || kitty @ launch --no-response --cwd=current --title=lazygit --copy-env lazygit"
t = ":sh kitty @ focus-window --match 'title:terminal and state:parent_active' || kitty @ launch --no-response --keep-focus --cwd=current --title=terminal"
i = ":sh kitty @ signal_child --match 'title:terminal and state:parent_active' SIGINT"
m = { r = ":sh kitty @ send-text --match 'title:terminal and state:parent_active' 'make run\n'", b = ":sh kitty @ send-text --match 'title:terminal and state:parent_active' 'make build\n'", t = ":sh kitty @ send-text --match 'title:terminal and state:parent_active' 'clear\nmake test\n'"}
s = ":pipe-to xargs -I {} kitty @ send-text --match title:terminal and state:parent_active '{}\n'"

[keys.normal.space.t]
f = ":toggle auto-format"
"." = ":toggle file-picker.hidden"
i = ":toggle lsp.display-inlay-hints"
s = ":toggle soft-wrap.enable"
n = ":toggle whitespace.render.newline all none"
z = ":toggle gutters.line-numbers.min-width 48 3"

[editor]
color-modes = true

[editor.whitespace.render]
newline = "all"

[editor.cursor-shape]
insert = "bar" # change cursor shape in insert mode

[editor.file-picker]
follow-symlinks = false

[editor.statusline]
center = ["version-control"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
