theme = "dark_plus"

[keys.normal]
C-j     = "page_down"
C-k     = ["page_up", "goto_window_top"]
G       = "goto_file_end"
C-l     = "goto_next_buffer"
C-h     = "goto_previous_buffer"
"tab"   = "expand_selection"
"S-tab" = "shrink_selection"
"F5"    = ":reload"
Z       = { Z = ":wq", Q = ":q!" }

[keys.select]
G = "goto_file_end"

[keys.normal.space]
w   = ":write"
q   = ":quit"
"." = "file_picker_in_current_buffer_directory"
l   = ":sh kitty @ launch --no-response --cwd=current --type=overlay --copy-env lazygit"

[keys.normal.space.t]
f   = ":toggle auto-format"
"." = ":toggle file-picker.hidden" # toggles ignoring hidden files
i   = ":toggle lsp.display-inlay-hints"
s   = ":toggle soft-wrap.enable"
z   = ":toggle gutters.line-numbers.min-width 52 3"
b   = ":toggle bufferline multiple never"

[keys.normal.C-space]
n = "@:o <C-r>%<C-w>"
x = "@:sh rm <C-r>%"
r = "@:sh mv <C-r>% <C-r>%<C-w>"
g = [":pipe-to cat > /tmp/helix-gpt", ":append-output cat /tmp/helix-gpt | aichat --role technical-writer"]
p = "@:sh pandoc --resource-path <C-r>%<C-w> --self-contained --metadata title='Preview' <C-r>% -o /tmp/md-preview.html && xdg-open /tmp/md-preview.html<ret>"
d = ":pipe echo -n $(date +%d-%m-%Y)"
t = ":sh kitty @ focus-window --match 'title:terminal and state:parent_active' || kitty @ launch --no-response --keep-focus --cwd=current --title=terminal"
a = ":sh kitty @ launch --no-response --title=aichat aichat --role technical-writer"
i = ":sh kitty @ signal-child --match 'title:terminal and state:parent_active' SIGINT"
m = { r = ":sh kitty @ send-text --match 'title:terminal and state:parent_active' 'make run\n'", b = ":sh kitty @ send-text --match 'title:terminal and state:parent_active' 'make build\n'", t = ":sh kitty @ send-text --match 'title:terminal and state:parent_active' 'clear\nmake test\n'"}
s = ":pipe-to xargs -I {} kitty @ send-text --match title:terminal and state:parent_active '{}\n'"

[editor]
color-modes = true
end-of-line-diagnostics = "hint"
bufferline = "multiple"
default-yank-register = "+"

[editor.whitespace.render]
newline = "all"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
follow-symlinks = false
hidden = false # don't ignore hidden files

[editor.statusline]
center = ["version-control"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.inline-diagnostics]
cursor-line = "warning"
