theme = "dark_plus"

[keys.normal]
G = "goto_file_end" # vim
Z = { Z = ":wq", Q = ":q!" } # vim
"#" = "toggle_comments"
"F5" = ":reload"

[keys.select]
G = "goto_file_end" # vim

[keys.normal.space]
w = ":write"
"." = "file_picker_in_current_buffer_directory"
"@" = ["select_all", ":pipe sort -t@ -k2,2"]
"+" = ["select_all", ":pipe sort -t+ -k2,2"]

[keys.normal.C-t]
l = ":sh kitty @ focus-window --match 'title:hx-lazygit and state:parent_active' || kitty @ launch --no-response --cwd=current --title=hx-lazygit lazygit"
t = ":sh kitty @ focus-window --match 'title:hx-terminal and state:parent_active' || kitty @ launch --no-response --cwd=current --title=hx-terminal"
i = ":sh kitty @ signal_child --match 'title:hx-lazygit and state:parent_active' SIGINT"
m = { r = ":sh kitty @ send-text --match 'title:hx-terminal and state:parent_active' 'make run\n'", b = ":sh kitty @ send-text --match 'title:hx-terminal and state:parent_active' 'make build\n'", t = ":sh kitty @ send-text --match 'title:hx-terminal and state:parent_active' 'clear\nmake test\n'"}
s = ":pipe-to xargs -I {} kitty @ send-text --match title:hx-terminal '{}\n'"

[keys.normal.space.t]
f = ":toggle auto-format"
i = ":toggle lsp.display-inlay-hints"
s = ":toggle soft-wrap.enable"
w = ":toggle whitespace.render all none"
z = ":toggle gutters.line-numbers.min-width 48 3"

[editor]
color-modes = true

[editor.cursor-shape]
insert = "bar" # change cursor shape in insert mode

[editor.file-picker]
hidden = false # don't ignore hidden files
follow-symlinks = false

[editor.statusline]
center = ["version-control"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
