# model: openai:gpt-4o
model: together:Qwen/Qwen3-235B-A22B-Instruct-2507-tput
keybindings: vi
compress_threshold: 16000
clients:
  # - type: openai
  - type: openai-compatible
    name: together
    api_base: https://api.together.xyz/v1
    models:
      - name: meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
        max_input_tokens: 131072
        input_price: 0
        output_price: 0
        supports_function_calling: true
      - name: deepseek-ai/DeepSeek-V3
        max_input_tokens: 131072
        input_price: 1.25
        output_price: 1.25
      - name: deepseek-ai/DeepSeek-R1
        max_input_tokens: 131072
        input_price: 3
        output_price: 7
      - name: Qwen/Qwen3-235B-A22B-Instruct-2507-tput
        max_input_tokens: 262144
        input_price: 0.2
        output_price: 0.6
