- name: Install Blender
  hosts: localhost
  become: false
  vars:
    bin_install_dir: /usr/local/bin
  tasks:
    - name: Install Blender
      block:
        - name: Create directory /usr/local/bin/blender-bin
          become: true
          ansible.builtin.file:
            path: "{{ bin_install_dir }}/blender-bin"
            state: directory

        - name: Download Blender and extract archive
          become: true
          ansible.builtin.unarchive:
            src: "https://download.blender.org/release/Blender4.3/blender-4.3.2-linux-x64.tar.xz"
            dest: "{{ bin_install_dir }}/blender-bin"
            remote_src: true
            creates: "{{ bin_install_dir }}/blender-bin/blender"
            extra_opts:
              - "--strip-components=1"

        - name: Create symlink to Blender binary
          become: true
          ansible.builtin.file:
            src: "{{ bin_install_dir }}/blender-bin/blender"
            dest: "{{ bin_install_dir }}/blender"
            state: link

        - name: Copy Blender desktop file
          ansible.builtin.copy:
            src: "{{ bin_install_dir }}/blender-bin/blender.desktop"
            dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/share/applications/blender.desktop"

        - name: Create ~/.icons directory
          ansible.builtin.file:
            path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.icons"
            state: directory

        - name: Copy Blender icon
          ansible.builtin.copy:
            src: "{{ bin_install_dir }}/blender-bin/blender.svg"
            dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.icons/blender.svg"
