- name: Install pipewire backport
  hosts: localhost
  tasks:
    - name: Install pipewire backport for Debian 12
      when: ansible_distribution == "Debian" and ansible_distribution_major_version == "12"
      block:
        - name: Add bookworm backports apt repository
          ansible.builtin.apt_repository:
            repo: deb http://deb.debian.org/debian bookworm-backports main

        - name: Install backports pipewire
          ansible.builtin.apt:
            name: pipewire
            state: latest
            default_release: bookworm-backports
