# https://github.com/rvaiya/keyd/issues/602 is why ignore_errors is true
- name: Playbook to install keyd
  hosts: localhost
  tasks:
    - name: Install keyd
      ignore_errors: true
      become: true
      block:
        - name: Download the keyd tar.gz file from GitHub
          ansible.builtin.get_url:
            url: https://github.com/rvaiya/keyd/archive/refs/tags/v2.4.3.tar.gz
            dest: /tmp/v2.4.3.tar.gz

        - name: Unarchive the tar.gz file
          ansible.builtin.unarchive:
            src: /tmp/v2.4.3.tar.gz
            dest: /tmp
            remote_src: true

        - name: Compile and install the software
          community.general.make:
            chdir: /tmp/keyd-2.4.3
            target: install

        - name: Copy default.conf to /etc/keyd/
          ansible.builtin.copy:
            src: ./default.conf
            dest: /etc/keyd/default.conf
            owner: root
            group: root
            mode: "0644"

        - name: Enable and start the keyd service
          ansible.builtin.systemd:
            name: keyd
            enabled: true
            state: started
