git:
  paging:
    colorArg: always
    pager: delta --paging=never --side-by-side

gui:
  nerdFontsVersion: "3"
  screenMode: half
  enlargedSideViewLocation: top
  showCommandLog: false

keybinding:
  universal:
    scrollUpMain-alt1: <c-k>
    scrollDownMain-alt1: <c-j>

customCommands:
  - key: "E"
    context: "files"
    command: "kitty @ launch --cwd=current $EDITOR ."
    subprocess: true
    description: "Open terminal editor in a new Kitty window in the current working directory"

promptToReturnFromSubprocess: false
