git:
  paging:
    colorArg: always
    pager: delta --paging=never --side-by-side

gui:
  nerdFontsVersion: "3"
  screenMode: half
  enlargedSideViewLocation: top
  showCommandLog: false

keybinding:
  universal:
    scrollUpMain-alt1: <c-k>
    scrollDownMain-alt1: <c-j>

promptToReturnFromSubprocess: false
