git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

refresher:
  refreshInterval: 3

gui:
  nerdFontsVersion: "3"
  enlargedSideViewLocation: "top"

os:
  editPreset: "helix"

customCommands:
  - key: "E"
    context: "files"
    command: "kitty @ launch --cwd=current $EDITOR ."
    subprocess: true
    description: "Open terminal editor in a new Kitty window in the current working directory"

promptToReturnFromSubprocess: false
